### ISSUE TITLE
Can read my movies

### ISSUE THREAD

**Issue by yecine06** [timhaak/docker-plex#73]
I have an issue when i try to play a video on the web interface it keeps loading and i never see the video.

Tried also to read it from iphone and it's still the same isse.

Here is the command line used to create the container 👍 
docker run --restart=always -d --name plex --net="host"  -v /mnt/storage/plex_config:/config -v /mnt/storage/media:/data -e RUN_AS_ROOT=TRUE -e SKIP_CHOWN_CONFIG=FALSE -e CHANGE_DIR_RIGHTS=TRUE timhaak/plex

here is the message i have :

There was a problem playing this item

have i done something wrong ?

**Comment by athieriot** [comment]
Hi there,

I have updated my Plex container yesterday and I seem to get the same issue as you.

The web UI works fine, I can access to it via all my devices but when I try to read anything it just doesn't work.

**Comment by timhaak** [comment]
Hi

I've tested this side and it seems to be working for me.

The only thing that took a while was the "CHANGE_DIR_RIGHTS=TRUE" as it had to change quite a coupe files.

Though I didn't have an interface till that was done.

Can you try without the flags? 

-e RUN_AS_ROOT=TRUE -e SKIP_CHOWN_CONFIG=FALSE -e CHANGE_DIR_RIGHTS=TRUE

**Comment by timhaak** [comment]
Ok going to close as assume what ever it was is fixed.

**Comment by yecine06** [comment]
Hello,

i have tried without the flags and still no luck the issue is still here

**Comment by yecine06** [comment]
@timhaak can you help  me ?

**Comment by timhaak** [comment]
Hi @yecine06 

I'm not sure how as I can't replicate it this side.

Also in the middle of some deadlines :)

Should calm down in about a week and then going to see if I can see anything
